CC=gcc
galemake: bonestructure.c byteswap.c fileheader.c galereader.c object.c pointertable.c rootnodes.c
	$(CC) bonestructure.c byteswap.c fileheader.c galereader.c object.c pointertable.c rootnodes.c -I.